filter:
    excluded_paths:
        - 'vendor/*'
build:
    environment:
        php: '5.5'
        variables:
            scrutinizer: true
            APP_ENV: testing
        hosts:
            confomo.test: '127.0.0.1'
        apache2:
            modules: ['rewrite']
            sites:
                laravel_app:
                    web_root: 'public/'
                    host: 'confomo.test'
    dependencies:
        before:
            - composer install --no-interaction
tools:
    php_cpd:
        min_lines: 5
        min_tokens: 70
    php_pdepend:
    php_changetracking:
    php_mess_detector:
